[build]
  image = "python:3.11"
  commands = [
    "pip install -r requirements.txt"
    echo "Hello, World!"
  ]

[run]
  command = [
    "uvicorn",
    "app:app",
    "--host", "0.0.0.0",
    "--port", "8080"
  ]
